#!/usr/bin/env bash
# configures an ubunutu server

export HOSTALIASES=~/.hosts
echo '127.0.0.2 localhost' > ~/.hosts
echo '8.8.8.8 facebook.com' >> ~/.hosts

ping -c 2 localhost
ping -c 2 facebook.com